### ISSUE TITLE
Crear botones nuevos en la ventana Nuevo Pedido

### ISSUE THREAD

**Issue by acasella03** [acasella03/Shopper2#38]
Crear los botones Buscar, Modificar y Eliminar con sus funcionalidades.

**Comment by acasella03** [comment]
Lo recomendable es:

- [x] Crear una nueva Ventana que puede llamarse Editar Pedido.
- [x] Agregar el botón modificar a Editar Pedido.
- [x] Agregar en la ventana Lista Pedidos un botón para ir a la ventana editar pedido.
- [x] Agregar en la ventana Lista Pedidos un botón que elimine un pedido seleccionado.

**Comment by JorgeAmestoy** [comment]
Vi que en el pull request lo ejecutaste corrigiendo los inconvenientes y creando una nueva ventana, genial Angi
